### ISSUE TITLE
AppSync Simulator: TypeError: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by appdatasoft** [bboure/serverless-appsync-simulator#88]
**Describe the bug**
Getting error while setting up serverless-appysnc-emulator on windows
AppSync Simulator: TypeError: Cannot read property 'path' of undefined
**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

  TypeError: Cannot read property 'path' of undefined
      at getAppSyncConfig (C:\Users\Administrator\Documents\appdatasoft\sumiventures\codemarket\parkyourselfbackend\node_modules\serverless-appsync-simulator\lib\getAppSyncConfig.js:247:38)
      at ServerlessAppSyncSimulator.initServer (C:\Users\Administrator\Documents\appdatasoft\sumiventures\codemarket\parkyourselfbackend\node_modules\serverless-appsync-simulator\lib\index.js:85:50) 
      at Client.<anonymous> (C:\Users\Administrator\Documents\appdatasoft\sumiventures\codemarket\parkyourselfbackend\node_modules\serverless-appsync-simulator\lib\index.js:147:14)
      at Client.emit (events.js:315:20)
      at Client.EventEmitter.emit (domain.js:482:12)
      at BunserBuf.<anonymous> (C:\Users\Administrator\Documents\appdatasoft\sumiventures\codemarket\parkyourselfbackend\node_modules\fb-watchman\index.js:90:14)
      at BunserBuf.emit (events.js:315:20)
      at BunserBuf.EventEmitter.emit (domain.js:482:12)
      at BunserBuf.process (C:\Users\Administrator\Documents\appdatasoft\sumiventures\codemarket\parkyourselfbackend\node_modules\bser\index.js:292:10)
      at C:\Users\Administrator\Documents\appdatasoft\sumiventures\codemarket\parkyourselfbackend\node_modules\bser\index.js:247:12
      at processTicksAndRejections (internal/process/task_queues.js:79:11)

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              12.18.2
     Framework Version:         2.12.0
     Plugin Version:            4.1.2
     SDK Version:               2.3.2
     Components Version:        3.4.1
 

**Screenshots**
![image](https://user-images.githubusercontent.com/41810092/114046582-cfb36680-983d-11eb-8645-1c766af334bb.png)

**Additional context**

**Comment by bboure** [comment]
Thank you @appdatasoft for raising this.

I see 2 different errors here
`Cannot read property 'path' of undefined` (title of hte ticket)
`Cannot read defaultAuthenticationtype of undefined` in the screenshot.

Could you please clarify the issue, show any output of the console, `serverless.yml` file, etc 

It would help understand the problem better

thank you

**Comment by skix123** [comment]
Hi, I'm also facing `Cannot read defaultAuthenticationtype of undefined` error.

Here's my `serverless.yml` file:
```
service: graphql-api
frameworkVersion: ^2.34.0

plugins:
    - serverless-appsync-plugin
    - serverless-plugin-typescript
    - serverless-appsync-simulator
    - serverless-offline

provider:
    name: aws
    region: eu-central-1
    runtime: nodejs14.x
    stage: ${opt:stage, 'local'}
    lambdaHashingVersion: '20201221'
    iam:
        role:
            statements:
                - Effect: Allow
                  Action:
                      - lambda:*
                  Resource:
                      - arn:aws:lambda:${self:provider.region}:*:*
    environment:
        REGION: '${self:provider.region}'
        STAGE: '${self:provider.stage}'
        APPSYNC_NAME: '${self:custom.defaultPrefix}-appsync'

custom:
    appSync: # appsync plugin configuration
        name: '${self:provider.environment.APPSYNC_NAME}'
        authenticationType: API_KEY
        serviceRole: 'AppSyncServiceRole'
        dataSources: ${file(resources/data-sources.yml)}
        mappingTemplates: ${file(resources/resolvers.yml)}
    appsync-simulator: # appsync-simulator configuration https://github.com/bboure/serverless-appsync-simulator#configuration
        apiKey: 'da2-fakeApiId1234567'
        port: 4000
    defaultPrefix: ${self:service}-${self:provider.stage}

functions:
    - ${file(resources/lambda-functions.yml)}

resources:
    - ${file(resources/roles.yml)} # Roles
```

The error occurs a few seconds after I run `sls offline start` - no API request is necessary.

**Comment by bboure** [comment]
@skix123  @appdatasoft Tryp to set the `SLS_DEBUG` env var to `*` (`export SLS_DEBUG="*"`) and run `sls offline start` again.
Then check the logs, look for `AppSync Simulator:` and try to see why there is no `defaultAuthenticationType`

you should see something like

```
AppSync Simulator: {
  appSync: {
    name: '********',
    apiKey: '0123456789',
    defaultAuthenticationType: { authenticationType: 'API_KEY' },
    additionalAuthenticationProviders: []
  },
  schema: {
    path: 'appsync/schema.graphql',
    content: '.....'
  },
  resolvers: [
    ...
  ],
  dataSources: [
	...
  ],
  functions: []
}
```

**Comment by appdatasoft** [comment]
> @skix123 @appdatasoft Tryp to set the `SLS_DEBUG` env var to `*` (`export SLS_DEBUG="*"`) and run `sls offline start` again.
> Then check the logs, look for `AppSync Simulator:` and try to see why there is no `defaultAuthenticationType`
> 
> you should see something like
> 
> ```
> AppSync Simulator: {
>   appSync: {
>     name: '********',
>     apiKey: '0123456789',
>     defaultAuthenticationType: { authenticationType: 'API_KEY' },
>     additionalAuthenticationProviders: []
>   },
>   schema: {
>     path: 'appsync/schema.graphql',
>     content: '.....'
>   },
>   resolvers: [
>     ...
>   ],
>   dataSources: [
> 	...
>   ],
>   functions: []
> }
> ```

@bboure 

Here is the log after SSL_BEBUG IS SET:
>serverless offline start
Serverless: To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^2.35.0")
Serverless: Invoke offline:start

AppSync Simulator: TypeError: Cannot read property 'path' of undefined
offline: Starting Offline: dev/us-east-2.
[offline] options: {
  allowCache: false,
  apiKey: 'd41d8abcdf00b204e9800998ecf1234',

**Comment by skix123** [comment]
@bboure nothing there. Here's the full log:
```Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall

Serverless: Load command delete-appsync
Serverless: Load command validate-schema
Serverless: Load command graphql-playground
Serverless: Load command deploy-appsync
Serverless: Load command update-appsync
Serverless: Load command offline
Serverless: Load command offline:start
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Deprecation warning: CLI options definitions were upgraded with "type" property (which could be one of "string", "boolean", "multiple"). Below listed plugins do not predefine type for introduced options:
             - ServerlessAppsyncPlugin for "clientId", "username", "password", "jwtToken", "apiKey", "port"
             - ServerlessOffline for "apiKey", "corsAllowHeaders", "corsAllowOrigin", "corsDisallowCredentials", "corsExposedHeaders", "disableCookieValidation", "enforceSecureCookies", "hideStackTraces", "host", "httpPort", "httpsProtocol", "lambdaPort", "noPrependStageInUrl", "noAuth", "ignoreJWTSignature", "noTimeout", "prefix", "printOutput", "resourceRoutes", "useChildProcesses", "useWorkerThreads", "websocketPort", "webSocketHardTimeout", "webSocketIdleTimeout", "useDocker", "layersDir", "dockerReadOnly", "functionCleanupIdleTimeSeconds", "allowCache", "dockerHost", "dockerHostServicePath", "dockerNetwork"
            Please report this issue in plugin issue tracker.
            Starting with next major release, this will be communicated with a thrown error.
            More Info: https://www.serverless.com/framework/docs/deprecations/#CLI_OPTIONS_SCHEMA
Serverless: Skipping variables resolution with old resolver (new resolver reported no more variables to resolve)
Serverless: Invoke offline:start
Serverless: Compiling with Typescript...
Serverless: Using local tsconfig.json
Serverless: Typescript compiled.
Serverless: Watching typescript files...
AppSync Simulator: AppSync endpoint: http://192.168.1.10:4000/graphql
AppSync Simulator: GraphiQl: http://192.168.1.10:4000
offline: Starting Offline: local/eu-central-1.
[offline] options: {
  allowCache: false,
  apiKey: 'd41d8cd98f00b204e9800998ecf8427e',
  corsAllowCredentials: true,
  corsAllowHeaders: [ 'accept', 'content-type', 'x-api-key', 'authorization' ],
  corsAllowOrigin: [ '*' ],
  corsExposedHeaders: [ 'WWW-Authenticate', 'Server-Authorization' ],
  disableCookieValidation: false,
  dockerHost: 'localhost',
  dockerHostServicePath: null,
  dockerNetwork: null,
  dockerReadOnly: true,
  enforceSecureCookies: false,
  functionCleanupIdleTimeSeconds: 60,
  hideStackTraces: false,
  host: 'localhost',
  httpPort: 3000,
  httpsProtocol: '',
  lambdaPort: 3002,
  layersDir: null,
  noAuth: false,
  noPrependStageInUrl: false,
  noTimeout: false,
  prefix: '',
  printOutput: true,
  resourceRoutes: false,
  useChildProcesses: false,
  useDocker: false,
  useWorkerThreads: false,
  webSocketHardTimeout: 7200,
  webSocketIdleTimeout: 600,
  websocketPort: 3001,
  stage: 'local',
  corsConfig: {
    credentials: true,
    exposedHeaders: [ 'WWW-Authenticate', 'Server-Authorization' ],
    headers: [ 'accept', 'content-type', 'x-api-key', 'authorization' ],
    origin: [ '*' ]
  }
}
offline: Offline [http for lambda] listening on http://localhost:3002
offline: Function names exposed for local invocation by aws-sdk:
           * getOrganizations: radvana-api-local-getOrganizations
           * getTeams: radvana-api-local-getTeams
[offline] Lambda Invocation Routes (for AWS SDK or AWS CLI):
           * POST http://localhost:3002/2015-03-31/functions/radvana-api-local-getOrganizations/invocations
           * POST http://localhost:3002/2015-03-31/functions/radvana-api-local-getTeams/invocations
[offline] Lambda Async Invocation Routes (for AWS SDK or AWS CLI):
           * POST http://localhost:3002/2014-11-13/functions/radvana-api-local-getOrganizations/invoke-async/
           * POST http://localhost:3002/2014-11-13/functions/radvana-api-local-getTeams/invoke-async/
TypeError: Cannot read property 'defaultAuthenticationType' of undefined
    at Object.getAllowedAuthTypes (/Users/SkiX/www/radvana-api/node_modules/amplify-appsync-simulator/lib/utils/auth-helpers/helpers.js:44:35)
    at Object.getAuthorizationMode (/Users/SkiX/www/radvana-api/node_modules/amplify-appsync-simulator/lib/utils/auth-helpers/current-auth-mode.js:18:38)
    at AppSyncSimulatorSubscriptionServer.authorizeRequest (/Users/SkiX/www/radvana-api/node_modules/amplify-appsync-simulator/lib/server/websocket-subscription.js:80:35)
    at AppSyncSimulatorSubscriptionServer.onConnect (/Users/SkiX/www/radvana-api/node_modules/amplify-appsync-simulator/lib/server/websocket-subscription.js:77:19)
    at WebsocketSubscriptionServer.<anonymous> (/Users/SkiX/www/radvana-api/node_modules/amplify-appsync-simulator/lib/server/subscription/websocket-server/server.js:134:59)
    at step (/Users/SkiX/www/radvana-api/node_modules/amplify-appsync-simulator/lib/server/subscription/websocket-server/server.js:63:23)
    at Object.next (/Users/SkiX/www/radvana-api/node_modules/amplify-appsync-simulator/lib/server/subscription/websocket-server/server.js:44:53)
    at /Users/SkiX/www/radvana-api/node_modules/amplify-appsync-simulator/lib/server/subscription/websocket-server/server.js:38:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/SkiX/www/radvana-api/node_modules/amplify-appsync-simulator/lib/server/subscription/websocket-server/server.js:34:12)
    at WebSocketServer.WebsocketSubscriptionServer.onSocketConnection (/Users/SkiX/www/radvana-api/node_modules/amplify-appsync-simulator/lib/server/subscription/websocket-server/server.js:114:71)
    at WebSocketServer.emit (events.js:315:20)
    at WebSocketServer.EventEmitter.emit (domain.js:486:12)
    at WebSocketServer.completeUpgrade (/Users/SkiX/www/radvana-api/node_modules/ws/lib/websocket-server.js:330:5)
    at WebSocketServer.handleUpgrade (/Users/SkiX/www/radvana-api/node_modules/ws/lib/websocket-server.js:246:10)
    at Server.upgrade (/Users/SkiX/www/radvana-api/node_modules/ws/lib/websocket-server.js:92:16)
    at Server.emit (events.js:315:20)
    at Server.EventEmitter.emit (domain.js:486:12)
    at onParserExecuteCommon (_http_server.js:695:14)
    at onParserExecute (_http_server.js:608:3)```

**Comment by skix123** [comment]
Node v14.14.0 if that matters

**Comment by skix123** [comment]
Maybe bumping `amplify-appsync-simulator` to the latest version would help?

**Comment by skix123** [comment]
Update: I had `serverless-plugin-typescript` plugin and it caused this error. Now I've remove it and have another one: `Error: UnauthorizedException: Missing authorization`

Log:

```
Error: UnauthorizedException: Missing authorization
    at Object.getAuthorizationMode (/Users/SkiX/www/radvana-api/node_modules/amplify-appsync-simulator/lib/utils/auth-helpers/current-auth-mode.js:56:11)
    at AppSyncSimulatorSubscriptionServer.authorizeRequest (/Users/SkiX/www/radvana-api/node_modules/amplify-appsync-simulator/lib/server/websocket-subscription.js:80:35)
    at AppSyncSimulatorSubscriptionServer.onConnect (/Users/SkiX/www/radvana-api/node_modules/amplify-appsync-simulator/lib/server/websocket-subscription.js:77:19)
    at WebsocketSubscriptionServer.<anonymous> (/Users/SkiX/www/radvana-api/node_modules/amplify-appsync-simulator/lib/server/subscription/websocket-server/server.js:134:59)
    at step (/Users/SkiX/www/radvana-api/node_modules/amplify-appsync-simulator/lib/server/subscription/websocket-server/server.js:63:23)
    at Object.next (/Users/SkiX/www/radvana-api/node_modules/amplify-appsync-simulator/lib/server/subscription/websocket-server/server.js:44:53)
    at /Users/SkiX/www/radvana-api/node_modules/amplify-appsync-simulator/lib/server/subscription/websocket-server/server.js:38:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/SkiX/www/radvana-api/node_modules/amplify-appsync-simulator/lib/server/subscription/websocket-server/server.js:34:12)
    at WebSocketServer.WebsocketSubscriptionServer.onSocketConnection (/Users/SkiX/www/radvana-api/node_modules/amplify-appsync-simulator/lib/server/subscription/websocket-server/server.js:114:71)
    at WebSocketServer.emit (events.js:315:20)
    at WebSocketServer.EventEmitter.emit (domain.js:486:12)
    at WebSocketServer.completeUpgrade (/Users/SkiX/www/radvana-api/node_modules/ws/lib/websocket-server.js:330:5)
    at WebSocketServer.handleUpgrade (/Users/SkiX/www/radvana-api/node_modules/ws/lib/websocket-server.js:246:10)
    at Server.upgrade (/Users/SkiX/www/radvana-api/node_modules/ws/lib/websocket-server.js:92:16)
    at Server.emit (events.js:315:20)
    at Server.EventEmitter.emit (domain.js:486:12)
    at onParserExecuteCommon (_http_server.js:695:14)
    at onParserExecute (_http_server.js:608:3)
```

As before, it occurs a few seconds after `sls offline start` but it doesn't crash the app and I'm able to make a graphql request and execute queries like nothing happened. However, error occurs at every request and it's hard to use terminal when it's filled with this wall of error messages :)

**Comment by bboure** [comment]
@skix123 OK, if you are using typescript or any bundler, you have to update the path where the simulator looks for compiled code.

Example:
```yml
appsync-simulator:
    location: .build
```

**Comment by skix123** [comment]
Still the same (`location: dist`)

**Comment by bboure** [comment]
OK, just realized your issue is about `defaultAuthenticationType`

can we please separate issues in 2 different tickets for clarity and tracking?

**Comment by appdatasoft** [comment]
> OK, just realized your issue is about `defaultAuthenticationType`
> 
> can we please separate issues in 2 different tickets for clarity and tracking?

@bboure looks like both the 2 issues are connected to each other.

**Comment by bboure** [comment]
Related issue/duplicate: #91

**Comment by maidanskyi** [comment]
@appdatasoft Hi
Have the same issue
Have you figured it out?

**Comment by trsrm** [comment]
It is failing because the plugin is [looking](https://github.com/bboure/serverless-appsync-simulator/blob/master/src/getAppSyncConfig.js#L226) for a `graphql.schema` file inside the `servicePath` which is `.build` in case of TypeScript project. By default, this folder **doesn't** contain the schema file.

If you are using the [serverless-plugin-typescript](https://github.com/serverless/serverless-plugin-typescript), then just update the package options with the following:
```yml
package:
    patterns:
        - 'schema.graphql'
```

**Comment by trsrm** [comment]
@bboure Please, add this to the documentation to simplify TS integration.
